# Generated by Django 3.2.3 on 2021-05-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Título'),
        ),
    ]
